# Inherits from base config and adds training-specific settings
_base_: "base.yaml"

# Enhanced training configuration
training:
  device: "cuda"  # Will auto-fallback to CPU if needed
  epochs: 50
  mixed_precision: true
  gradient_clipping: 1.0
  checkpoint:
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"
  early_stopping:
    monitor: "val_loss"
    patience: 7
    verbose: true
  lr_scheduler:
    name: "CosineAnnealingLR"
    T_max: 10
    eta_min: 1e-6

# Data augmentation enhancements
augmentations:
  train:
    - name: "HorizontalFlip"
      params: {p: 0.5}
    - name: "VerticalFlip"
      params: {p: 0.5}
    - name: "ShiftScaleRotate"
      params: {shift_limit: 0.1, scale_limit: 0.2, rotate_limit: 15, p: 0.7}
    - name: "RandomBrightnessContrast"
      params: {brightness_limit: 0.2, contrast_limit: 0.2, p: 0.5}
    - name: "GaussNoise"
      params: {var_limit: (10.0, 50.0), p: 0.3}
    - name: "Cutout"
      params: {max_h_size: 32, max_w_size: 32, num_holes: 8, p: 0.5}

# Dataset-specific settings
data:
  train:
    batch_size: 16  # Increased for modern GPUs
    num_workers: 8
    shuffle: true
    pin_memory: true
  val:
    batch_size: 8
    num_workers: 4
    pin_memory: true

# Experiment tracking
logging:
  wandb:
    enabled: true
    project: "steel-defect-detection"
    tags: ["unet", "resnet18"]
    notes: "Training with enhanced augmentations"